---
  
 - name: Install Python and Dependencies
   apt: pkg={{ item }} state=latest
   with_items:
       - python
       - python-setuptools
       - python-pip
       - python-dev
       - git
       - libncurses-dev
       - libreadline6
       - libreadline6-dev
       - libreadline-gplv2-dev
       - libncursesw5-dev
       - libssl-dev
       - libsqlite3-dev
       - tk-dev
       - libgdbm-dev
       - libc6-dev
       - libbz2-dev
       - build-essential

 - name: Install Packages (pip method)
   pip: name={{ item }} state=latest
   with_items:
       - virtualenv
       - cloudmesh_client

 - name: Install Packages (easy_install method)
   easy_install: name=pycrypto
