---
- hosts: local
  tasks:
  - name: Install Python
    apt: pkg=python state=latest update_cache=true
  - name: Install Python-setuptools
    apt: pkg=python-setuptools state=latest update_cache=true
  - name: Install Python-Pip
    apt: pkg=python-pip state=latest update_cache=true
  - name: Install Python-Dev
    apt: pkg=python-dev state=latest update_cache=true
  - name: Install Git
    apt: pkg=git state=latest update_cache=true
  - name: Install libncurses-dev
    apt: pkg=libncurses-dev state=latest update_cache=true
  - name: Install Libreadline6
    apt: pkg=libreadline6 state=latest update_cache=true
  - name: Install Libreadline6-dev
    apt: pkg=libreadline6-dev state=latest update_cache=true
  - name: Install VirtualEnv
    pip: name=virtualenv state=latest
  - name: Install pycrypto
    easy_install: name=pycrypto
  - name: Install libreadline-gplv2-dev
    apt: pkg=libreadline-gplv2-dev state=latest update_cache=true
  - name: Install libncursesw5-dev
    apt: pkg=libncursesw5-dev state=latest update_cache=true
  - name: Install libssl-dev
    apt: pkg=libssl-dev state=latest update_cache=true
  - name: Install libsqlite3-dev
    apt: pkg=libsqlite3-dev state=latest update_cache=true
  - name: Install tk-dev
    apt: pkg=tk-dev state=latest update_cache=true
  - name: Install libgdbm-dev
    apt: pkg=libgdbm-dev state=latest update_cache=true
  - name: Install libc6-dev
    apt: pkg=libc6-dev state=latest update_cache=true
  - name: Install libbz2-dev
    apt: pkg=libbz2-dev state=latest update_cache=true
  - name: Install build-essential
    apt: pkg=build-essential state=latest update_cache=true
  - name: Create VirtualENV and Install Cloudmesh_Client
    pip: name=cloudmesh_client virtualenv=/home/ubuntu/ENV virtualenv_command=/usr/local/bin/virtualenv
  - name: Activate VirtualENV
    shell: . /home/ubuntu/ENV/bin/activate
  - name: Run CM Help
    shell: /home/ubuntu/ENV/bin/cm help
